name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check (${{ matrix.system }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            system: x86_64-linux
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@b85815f71a6de0ddee80b8a80a98d43f4bcc66c7 # v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.34.6/install
      - run: nix flake check --no-update-lock-file --print-build-logs
      - run: nix run --no-update-lock-file .# -- shell .
      - name: Check PR title
        if: github.event_name == 'pull_request'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: nix run --no-update-lock-file .# -- title "$PR_TITLE"
